### PR TITLE
Device ready for maru-0.7

### PR DESCRIPTION
**Pull request by pintaf**

### CODE REVIEW

**Review by utzcoz — CHANGES_REQUESTED** [review]
The check result of `CONFIG=kernel/google/marlin/arch/arm64/configs/maru_marlin_defconfig lxc-checkconfig` is:

```
WARNING: Unable to detect version from configuration, assuming latest

--- Namespaces ---
Namespaces: enabled
Utsname namespace: missing
Ipc namespace: required
Pid namespace: required
User namespace: missing
Network namespace: missing
```
The `Ipc namespace` and `Pid namespace` is required, but it is missing. We should add it to pass lxc config check.

**Comment by utzcoz** [comment]
The configs for those two namespace are:

```
CONFIG_PID_NS=y
CONFIG_IPC_NS=y
```

**Comment by pintaf** [comment]
> The configs for those two namespace are:
> 
> ```
> CONFIG_PID_NS=y
> CONFIG_IPC_NS=y
> ```

About that, in the [maru porting guide](https://maruos.com/docs/developer/porting.html#android-kernel-codename) these are not mentionned.

Also, we are based on lxc 1 in maru wheen lxc-checkconfig is installed (for me) from apt.
Do you think these IPC and Pid namespace requirement comes from a newer version of lxc and might not be needed for LXC1, or is it just something forgotten in porting guides ?

@pdsouza FYI

**Comment by pdsouza** [comment]
Typically those are selected by default with `CONFIG_NAMESPACES=y` _unless_ there is a line like `# CONFIG_PID_NS is not set` which I can see in your [first commit](https://github.com/maruos/android_kernel_google_marlin/pull/3/commits/0e005720c28628bd2abc1d5e482e51af006a3e1e#diff-f533382d35c8b80f681643607afbf52e707d2dea50cad8876f7ba4a823063266R33). Typically you just need to remove that line and it will work. Things may have changed with the newer kernels.

`CONFIG_PID_NS` is definitely a requirement for isolating all the Linux processes and running `systemd` as PID 1 in LXC regardless of which version of LXC.

**Comment by utzcoz** [comment]
I always use `CONFIG=kernel/google/marlin/arch/arm64/configs/maru_marlin_defconfig lxc-checkconfig` to check the `defconfig` for lxc whether there are required but missing configs.

**Comment by pdsouza** [comment]
Yeah, best approach is to just use `lxc-checkconfig`.

**Comment by pintaf** [comment]
OK thanks. Good to know !

**Pull request merged**
