### PR TITLE
sailfish/marlin: Enable all namespaces used by lxc

### PR DESCRIPTION
**Pull request by utzcoz**

### CODE REVIEW

**Comment by utzcoz** [comment]
It will fix `lxc-start --name default` can't work correctly.

**Comment by utzcoz** [comment]
In porting doc, we should let developer ensure all namespace of lxc used are enabled.

**Review by pdsouza — APPROVED** [review]
I think the only required options for the way Maru uses containers is UTS, PID, and IPC. USER and NET should be optional (UIDs are offset by a large number in custom `useradd` config on desktop, and we share same network namespace with Android for networking), but it doesn't hurt to include them in case we want to experiment with using them in the future.

**Comment by pdsouza** [comment]
> In porting doc, we should let developer ensure all namespace of lxc used are enabled.

Is this good? https://github.com/maruos/maruos/pull/156

**Comment by utzcoz** [comment]
> > In porting doc, we should let developer ensure all namespace of lxc used are enabled.
> 
> Is this good? [maruos/maruos#156](https://github.com/maruos/maruos/pull/156)

It's good. 
Thanks @pdsouza for reviewing.

**Pull request merged**
